### PR TITLE
improved portability, reduced unnecessary code, started factoring out

### PR DESCRIPTION
**Pull request by Robstersgaming**

### CODE REVIEW

**Comment by Robstersgaming** [comment]
Hey, unrelated to the pull request but I am really interested on how you created the outlook page. Did you pull assets from an actual outlook site or make it from scratch? I'd love to hear about the process 

Thanks,
Robby

**Comment by aarav2you** [comment]
> Hey, unrelated to the pull request but I am really interested on how you created the outlook page. Did you pull assets from an actual outlook site or make it from scratch? I'd love to hear about the process
> 
> Thanks,
> Robby

Hi Robby,
Thanks for contributing once again! I downloaded the page from outlook (`Ctrl+ S`),  then opened the `.html` page once so it creates its linked files. They will reside in `Sign into Outlook_files` folder. Then I removed unnecessary files, removed all the errors and added a `{{email}}` variable right next to the non-functional arrow-sign on the password page. So it was fully copied, except a few modifications.

**Comment by Robstersgaming** [comment]
> > Hey, unrelated to the pull request but I am really interested on how you created the outlook page. Did you pull assets from an actual outlook site or make it from scratch? I'd love to hear about the process
> 
> > 
> 
> > Thanks,
> 
> > Robby
> 
> 
> 
> Hi Robby,
> 
> Thanks for contributing once again! I downloaded the page from outlook (`Ctrl+ S`),  then opened the `.html` page once so it creates its linked files. They will reside in `Sign into Outlook_files` folder. Then I removed unnecessary files, removed all the errors messages and added a `{{email}}` variable right next to the non-functional arrow-sign on the password page. So it was fully copied, except a few modifications.

￼interesting thank you for the info :)

**Review by aarav2you — APPROVED** [review]
Thanks for contributing again! In the long run, this will make it more portable and fish.py won't be so big. Thanks for improving our code too!

**Comment by aarav2you** [comment]
@Robstersgaming Hi robert, I am extremely sorry but I have seen to accidentally removed your pull request when I was meaning to remove one of my commits. Could you open a pull request again? This won't repeat in the future. Thanks!

**Pull request merged**
